<<<<<<< HEAD
server:
  port : 8080
=======

>>>>>>> 584b750135f190d8f44be30d7637a490158a2a3e

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/paysheet-dev
      client: mongodb://localhost:27017
      database: paysheet-dev

mvc:
   pathmatch:
     matching-strategy: ant_path_matcher

jwt:
 jwtSecret: intellidocsSecretKey
 jwtExpirationMs: 36000000
 
  